const referencePointGroup=L.layerGroup().addTo(map);
let referencePoints=[];
const LS_REFERENCE_POINTS='webgis_geo_reference_points_v1';
function saveReferencePoints(){localStorage.setItem(LS_REFERENCE_POINTS,JSON.stringify(referencePoints));}
function formatCoordinate(value,decimals=6){return Number(value).toLocaleString('pt-BR',{minimumFractionDigits:decimals,maximumFractionDigits:decimals});}
function getUtmProj(zone){return `+proj=utm +zone=${zone} +south +ellps=GRS80 +units=m +no_defs`;}
function latLngToUtm(lat,lng,zone){const r=proj4('EPSG:4326',getUtmProj(zone),[lng,lat]);return {easting:r[0],northing:r[1]};}
function utmToLatLng(easting,northing,zone){const r=proj4(getUtmProj(zone),'EPSG:4326',[easting,northing]);return {lng:r[0],lat:r[1]};}
function pointPopupHtml(point){const utm=latLngToUtm(point.lat,point.lng,point.zone||24);return `<div class="point-popup-table"><b>${escapeHtml(point.label||'Ponto de referência')}</b><br>Latitude: ${formatCoordinate(point.lat)}<br>Longitude: ${formatCoordinate(point.lng)}<br>UTM ${point.zone||24}S — E: ${formatCoordinate(utm.easting,2)} m<br>UTM ${point.zone||24}S — N: ${formatCoordinate(utm.northing,2)} m${point.accuracy?`<br>Precisão estimada: ${formatCoordinate(point.accuracy,1)} m`:''}<br>Origem: ${escapeHtml(point.source||'Manual')}</div>`;}
function renderReferencePoints(){referencePointGroup.clearLayers();referencePoints.forEach(point=>{L.marker([point.lat,point.lng],{title:point.label||'Ponto de referência'}).bindPopup(pointPopupHtml(point)).addTo(referencePointGroup);});const status=document.getElementById('pointStatus');if(status)status.textContent=referencePoints.length?`${referencePoints.length} ponto(s) de referência adicionado(s).`:'Nenhum ponto de referência adicionado.';}
function addReferencePoint(point,zoom=true){referencePoints.push({id:point.id||uid(),label:point.label||`Ponto ${referencePoints.length+1}`,lat:Number(point.lat),lng:Number(point.lng),zone:Number(point.zone||24),accuracy:point.accuracy?Number(point.accuracy):null,source:point.source||'Manual',createdAt:new Date().toISOString()});saveReferencePoints();renderReferencePoints();if(zoom)map.setView([point.lat,point.lng],Math.max(map.getZoom(),16));}
function loadReferencePoints(){try{const saved=JSON.parse(localStorage.getItem(LS_REFERENCE_POINTS)||'[]');if(Array.isArray(saved))referencePoints=saved;}catch(e){referencePoints=[]}renderReferencePoints();}
function openUtmModal(){const modal=document.getElementById('utmModal');modal?.classList.add('open');modal?.setAttribute('aria-hidden','false');}
function closeUtmModal(){const modal=document.getElementById('utmModal');modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true');}
function bindReferencePointEvents(){
 document.getElementById('btnGpsLocation')?.addEventListener('click',()=>{const status=document.getElementById('pointStatus');if(!navigator.geolocation){alert('Este dispositivo ou navegador não oferece suporte à localização.');return;}if(location.protocol!=='https:'&&location.hostname!=='localhost'&&location.protocol!=='file:'){alert('A localização por GPS exige HTTPS.');return;}if(status)status.textContent='Obtendo localização do dispositivo...';navigator.geolocation.getCurrentPosition(position=>{const {latitude,longitude,accuracy}=position.coords;addReferencePoint({label:'Localização do dispositivo',lat:latitude,lng:longitude,zone:24,accuracy,source:'GPS / dispositivo'});if(status)status.textContent=`Localização adicionada. Precisão estimada: ${formatCoordinate(accuracy,1)} m.`;},error=>{const messages={1:'Permissão de localização negada.',2:'Localização indisponível.',3:'Tempo limite excedido ao obter localização.'};const message=messages[error.code]||error.message||'Falha ao obter localização.';if(status)status.textContent=message;alert(message);},{enableHighAccuracy:true,timeout:20000,maximumAge:0});});
 document.getElementById('btnOpenUtm')?.addEventListener('click',openUtmModal);document.getElementById('btnCloseUtm')?.addEventListener('click',closeUtmModal);document.getElementById('btnCancelUtm')?.addEventListener('click',closeUtmModal);
 document.getElementById('btnAddUtmPoint')?.addEventListener('click',()=>{const easting=Number(document.getElementById('utmEasting').value),northing=Number(document.getElementById('utmNorthing').value),zone=Number(document.getElementById('utmZone').value),label=document.getElementById('utmLabel').value.trim()||`Ponto UTM ${referencePoints.length+1}`,status=document.getElementById('utmStatus');if(!Number.isFinite(easting)||!Number.isFinite(northing)){status.textContent='Informe valores válidos para Este e Norte.';return;}if(easting<100000||easting>900000||northing<0||northing>10000000){status.textContent='As coordenadas informadas estão fora da faixa UTM esperada.';return;}try{const {lat,lng}=utmToLatLng(easting,northing,zone);addReferencePoint({label,lat,lng,zone,source:'UTM SIRGAS 2000'});status.textContent=`Ponto adicionado: ${formatCoordinate(lat)}, ${formatCoordinate(lng)}.`;closeUtmModal();document.getElementById('utmEasting').value='';document.getElementById('utmNorthing').value='';document.getElementById('utmLabel').value='';}catch(err){status.textContent='Erro na conversão das coordenadas: '+(err.message||err);}});
 document.getElementById('btnClearPoints')?.addEventListener('click',()=>{if(referencePoints.length&&confirm('Remover todos os pontos de referência?')){referencePoints=[];saveReferencePoints();renderReferencePoints();}});
 document.getElementById('utmModal')?.addEventListener('click',event=>{if(event.target.id==='utmModal')closeUtmModal();});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.getElementById('utmModal')?.classList.contains('open'))closeUtmModal();});
}
window.addEventListener('DOMContentLoaded',()=>{bindReferencePointEvents();loadReferencePoints();});
